apiVersion: broker.amq.io/v2alpha2
kind: ActiveMQArtemisAddress
metadata:
  name: phil-test
spec:
  addressName: phil-test
  queueName: phil-test
  removeFromBrokerOnDelete: true
  routingType: anycast
