apiVersion: broker.amq.io/v2alpha4
kind: ActiveMQArtemis
metadata:
  name: phil-broker
spec:
  acceptors:
    - enabledProtocols: amqp
      expose: true
      name: amqp
      port: 5672
      protocols: amqp
  adminPassword: admin
  adminUser: admin
  console:
    expose: true
  deploymentPlan:
    size: 2
    persistenceEnabled: false
    requireLogin: false
    messageMigration: true
    managementRBACEnabled: false
    journalType: nio
    jolokiaAgentEnabled: true
    image: placeholder
    storage:
      size: 1Gi
  upgrades:
    enabled: true
    minor: true
